apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretRefName }}
type: Opaque
data:
  ATLAS_URI: {{ .Values.secret.atlasUri }}
  HASH_KEY: {{ .Values.secret.hashKey }}        
  JWT_SECRET_KEY: {{ .Values.secret.jwtSecretKey }}
  PORT: {{ .Values.secret.port }}