apiVersion: v1
kind: Service
metadata:
  name: {{ include "learner-insights.fullname" . }}-backend
  labels:
    app: {{ include "learner-insights.name" . }}-backend
    tier: {{ include "learner-insights.name" . }}-backend
    environment: {{ .Values.environment }}
spec:
  selector:
    app: {{ include "learner-insights.name" . }}-backend
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}