apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: learner-insights
type: Opaque
data:
  ATLAS_URI: bW9uZ29kYjovL3Jvb3Q6cm9vdEBtb25nby0wLm1vbmdvLm1vbmdvZGIuc3ZjLmNsdXN0ZXIubG9jYWw6MjcwMTcvbGVhcm5lci1pbnNpZ2h0cz9hdXRoU291cmNlPWFkbWlu
  HASH_KEY: dGhpc0lzTXlIYXNoS2V5Cg==           
  JWT_SECRET_KEY: dGhpc0lzTXlKd3RTZWNyZXRLZXkK
  PORT: MzAwMQo=