apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: learner-insights
  labels:
    app: backend
    tier: backend
    environment: production
spec:
  selector:
    app: backend
  ports:
  - port: 3001
    targetPort: 3001
  type: LoadBalancer