apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None                # This makes it headless
  selector:
    app: mongo
